---
title: "3_Appariement"
author: "P. de Vreyer (PSL, Dauphine)"
date: "`r Sys.Date()`"
output: html_document
---

## Propensity score ?

### Conditions

-   Pas tirage aléatoire
-   Bcp d'informations sur les personnes

Pour rappel, l'intérêt du tirage au sort est s'assurer, qu'**en moyenne, personnes traités et non-traités ont les mêmes caractéristiques** donc différences observées = traitement

Ici, on constitue un groupe comparable à partir des observables

### Mise en oeuvre

-   Rechercher des variables qui expliquent la probabilité de participation au programme, sans être modifiées par celui-ci

-   Rosenbaum et Rubin (1983) : cette statistique - le score de propension

    -   Suffit pour résumer toutes les dimensions et créer des jumeaux dans chaque groupe

    -   Est plus simple que de trouver un individu avec toutes les caractéristiques observables similaires

-   Certains groupes peuvent ne pas être être appariés à l'issue, proba trop forte ou trop faible de participer- ces personnes **ne se conforment pas à la condition de support commun**

## En pratique 

### Calcul

-   On note en général l'espérance du traitement potentiel, p, selon le traitement ou non (T) et les caractéristiques, X, $E(Y^p|T,X)$
-   tel que $ATT = E(Y^1|T=1,X) - E(Y^0|T=1,X) = E(Y^1|T=1,X) - E(Y^0|T=0,X) + E(Y^0|T=0,X) - E(Y^0|T=1,X)$ où seul $E(Y^0|T=1,X)$ ne peut pas être observé

### Conditions

-   "Support" commun, les individus en dehors ne peuvent pas être appariés (proba trop forte ou faible de participation)

-   Condition d'équilibre des échantillons : les valeurs moyennes des observables doivent être proches pour des scores identiques

-   Indépendance conditionnelle (aux caractéristiques observables) $E(Y^0|T=1,X) = E(Y^0|T=0,X)$ et $E(Y^1|T=1,X) = E(Y^1|T=0,X)$

La dernière est d'autant plus vraie que les deux premières sont respectées et permet d'annuler le biais dans le calcul de l'ATT.

### Mise en oeuvre

Méthodes :

-   Voisin le plus proche ? Simple mais risque que la valeur observée de l'impact soit spécifique pour ce voisin en particulier -\> on souhaiterait une valeur moyenne de l'impact

-   K plus proches voisins ou toutes les personnes non-traitées (méthode du noyau) -\> formule générale avec une pondération \omega qui dépend de la proximité entre les scores (à partir de fonctions noyau, comme le noyau Gaussien)

-   $ATT_{PSM} = \frac{1}{N_T} \Sigma_i [Y_{i}^1 - \Sigma_j \omega_j Y_{j}^0 ]$

## Limites

-   Sélection **uniquement** sur observables, pb des facteurs inobservés, par exemple la motivation -\> si la la crédibilité de l'hypothèse d'indépendance conditionnelle n'est pas respectée, pareil que de faire une régression linéaire avec les variables du score ...

-   Région de support commun trop étroite -\> risque sur le nombre d'observations et le respect des caratéristiques moyennes
